[language-server.clangd]
command = "clangd"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-langauge-server=info"
LOG_FILE = "/tmp/completion.log"

# append langage server to existed languages
[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]

[[language]]
name = "git-commit"
language-servers = [ "scls" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "scls" ]

[[language]]
name = "cpp"
auto-format = false
file-types = ["cpp", "h", "c"]
indent = { tab-width = 4, unit = "  " }
language-servers = [ "clangd", "scls" ]
# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"
